apiVersion: v1
kind: Service
metadata:
  name: recruitment-app-service
  labels:
    app: recruitment-app
  namespace: iyas-ns  
spec:
  selector: 
    app: recruitment-app
  ports:  
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
