apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr-app
  template:
    metadata:
      labels:
        app: hr-app
    spec:
      containers:
        - name: hr-app
          image: hr-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: hr-app-config
                  key: PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: hr-app-config
                  key: DB_NAME
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: hr-app-secrets
                  key: MONGO_URI
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
