apiVersion: apps/v1
kind: Deployment
metadata:
  name: recr-mongo-deployment
  labels:
    app: recr-mongo
  namespace: iyas-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recr-mongo
  template:
    metadata:
      labels:
        app: recr-mongo
    spec:
      containers:
        - name: recr-mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: recr-secret