apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo-app
  namespace: iyas-ns  
spec:
  selector: 
    app: recr-mongo 
  ports:  
    - protocol: TCP   
      port: 27017
      targetPort: 27017     
  type: ClusterIP 