apiVersion: v1
kind: Secret
metadata:
  name: recr-secret
  namespace: iyas-ns
type: Opaque
stringData:
  MONGO_APP_USERNAME: "hrapp"
  MONGO_APP_PASSWORD: "hrapp_123"
  MONGO_ROOT_USERNAME: "root"
  MONGO_ROOT_PASSWORD: "root_123"
  MONGO_URI: "mongodb://hrapp:hrapp_123@mongodb:27017/hr_system?authSource=hr_system"